// <auto-generated />
using System;
using League_of_Legends_Tournament_Hosting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace League_of_Legends_Tournament_Hosting.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20260505014346_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GamerTag = "IvanCoach",
                            HiredAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivan Horvat",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 2,
                            GamerTag = "MarkoPeric",
                            HiredAt = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marko Perić",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            GamerTag = "LukaN",
                            HiredAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luka Novak",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 4,
                            GamerTag = "TomiBlazer",
                            HiredAt = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomislav Blažević",
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 5,
                            GamerTag = "AnteJ",
                            HiredAt = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ante Jurić",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 6,
                            GamerTag = "NikoSaric",
                            HiredAt = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikola Šarić",
                            YearsOfExperience = 11
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HiredAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petra Kovač",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 2,
                            HiredAt = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ana Babić",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 3,
                            HiredAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maja Tomić",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 4,
                            HiredAt = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sara Marić",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 5,
                            HiredAt = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iva Paulić",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 6,
                            HiredAt = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dora Knežević",
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferredPosition")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryPosition")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId1")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId3")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId4")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId1");

                    b.HasIndex("TeamId3");

                    b.HasIndex("TeamId4");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SponsorshipAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "esports@ht.hr",
                            ContactPhone = "+385 1 111 2222",
                            ContractEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HT Telekom",
                            SponsorshipAmount = 5000.00m,
                            Website = "https://www.t.ht.hr"
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "sponsorships@razer.com",
                            ContactPhone = "+1 800 123 4567",
                            ContractEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer",
                            SponsorshipAmount = 8000.00m,
                            Website = "https://www.razer.com"
                        },
                        new
                        {
                            Id = 3,
                            ContactEmail = "esports@redbull.com",
                            ContactPhone = "+43 662 6582 0",
                            ContractEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Red Bull",
                            SponsorshipAmount = 10000.00m,
                            Website = "https://www.redbull.com"
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrizePool")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BookingFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 35",
                            BookingFrom = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingTo = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 500,
                            City = "Zagreb",
                            ContactEmail = "contact@zagrebesports.hr",
                            ContactPhone = "+385 1 234 5678",
                            IsAvailable = true,
                            Name = "Zagreb Esports Arena"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Domovinskog rata 12",
                            BookingFrom = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingTo = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 300,
                            City = "Split",
                            ContactEmail = "info@splitgaming.hr",
                            ContactPhone = "+385 21 345 6789",
                            IsAvailable = true,
                            Name = "Split Gaming Hub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Korzo 5",
                            BookingFrom = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingTo = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 200,
                            City = "Rijeka",
                            ContactEmail = "hello@rjekalanc.hr",
                            ContactPhone = "+385 51 456 7890",
                            IsAvailable = true,
                            Name = "Rijeka LAN Center"
                        });
                });

            modelBuilder.Entity("TeamPlayers", b =>
                {
                    b.Property<int>("PlayersListId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayersListId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("TournamentSponsors", b =>
                {
                    b.Property<int>("SponsorsListId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("SponsorsListId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentSponsors");
                });

            modelBuilder.Entity("TournamentTeams", b =>
                {
                    b.Property<int>("TeamsListId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("TeamsListId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentTeams");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Player", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany("ConfirmedPlayers")
                        .HasForeignKey("TeamId");

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId1");

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany("StartingPlayers")
                        .HasForeignKey("TeamId3");

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany("SubstitutePlayers")
                        .HasForeignKey("TeamId4");

                    b.OwnsOne("League_of_Legends_Tournament_Hosting.Models.AccountInformation", "AccountInformation", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.Property<int>("LeagueTier")
                                .HasColumnType("int");

                            b1.Property<int>("Region")
                                .HasColumnType("int");

                            b1.Property<string>("RiotTag")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SummonerName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("AccountInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Sponsor", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", null)
                        .WithMany("Sponsors")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Team", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", null)
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId");

                    b.Navigation("Coach");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Tournament", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TeamPlayers", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentSponsors", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentTeams", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Team", b =>
                {
                    b.Navigation("ConfirmedPlayers");

                    b.Navigation("Players");

                    b.Navigation("StartingPlayers");

                    b.Navigation("SubstitutePlayers");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Tournament", b =>
                {
                    b.Navigation("Sponsors");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
