// <auto-generated />
using System;
using League_of_Legends_Tournament_Hosting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace League_of_Legends_Tournament_Hosting.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    partial class TournamentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GamerTag = "IvanCoach",
                            HiredAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivan Horvat",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 2,
                            GamerTag = "MarkoPeric",
                            HiredAt = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marko Perić",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            GamerTag = "LukaN",
                            HiredAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luka Novak",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 4,
                            GamerTag = "TomiBlazer",
                            HiredAt = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomislav Blažević",
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 5,
                            GamerTag = "AnteJ",
                            HiredAt = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ante Jurić",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 6,
                            GamerTag = "NikoSaric",
                            HiredAt = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikola Šarić",
                            YearsOfExperience = 11
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HiredAt = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petra Kovač",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 2,
                            HiredAt = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ana Babić",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 3,
                            HiredAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maja Tomić",
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 4,
                            HiredAt = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sara Marić",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 5,
                            HiredAt = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iva Paulić",
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 6,
                            HiredAt = new DateTime(2019, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dora Knežević",
                            YearsOfExperience = 10
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreferredPosition")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GamerTag = "MirkoH",
                            JoinedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mirko Horvat",
                            PreferredPosition = 0,
                            Role = 0,
                            SecondaryPosition = 2
                        },
                        new
                        {
                            Id = 2,
                            GamerTag = "PetarMark",
                            JoinedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petar Marković",
                            PreferredPosition = 2,
                            Role = 0,
                            SecondaryPosition = 1
                        },
                        new
                        {
                            Id = 3,
                            GamerTag = "AnaH",
                            JoinedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ana Horvat",
                            PreferredPosition = 1,
                            Role = 0,
                            SecondaryPosition = 3
                        },
                        new
                        {
                            Id = 4,
                            GamerTag = "JovanN",
                            JoinedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jovan Nikolić",
                            PreferredPosition = 3,
                            Role = 0,
                            SecondaryPosition = 4
                        },
                        new
                        {
                            Id = 5,
                            GamerTag = "MarkoPetro",
                            JoinedAt = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marko Petrović",
                            PreferredPosition = 4,
                            Role = 1,
                            SecondaryPosition = 0
                        },
                        new
                        {
                            Id = 6,
                            GamerTag = "FilipA",
                            JoinedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Filip Aleksić",
                            PreferredPosition = 1,
                            Role = 2,
                            SecondaryPosition = 2
                        },
                        new
                        {
                            Id = 7,
                            GamerTag = "IvaF",
                            JoinedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iva Filipović",
                            PreferredPosition = 3,
                            Role = 2,
                            SecondaryPosition = 1
                        },
                        new
                        {
                            Id = 8,
                            GamerTag = "LukaK",
                            JoinedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luka Kovač",
                            PreferredPosition = 0,
                            Role = 0,
                            SecondaryPosition = 1
                        },
                        new
                        {
                            Id = 9,
                            GamerTag = "PetraN",
                            JoinedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petra Novak",
                            PreferredPosition = 2,
                            Role = 0,
                            SecondaryPosition = 4
                        },
                        new
                        {
                            Id = 10,
                            GamerTag = "MarijaB",
                            JoinedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marija Bjelica",
                            PreferredPosition = 1,
                            Role = 0,
                            SecondaryPosition = 2
                        },
                        new
                        {
                            Id = 11,
                            GamerTag = "NikolaR",
                            JoinedAt = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nikola Radivojević",
                            PreferredPosition = 3,
                            Role = 1,
                            SecondaryPosition = 1
                        },
                        new
                        {
                            Id = 12,
                            GamerTag = "SandraT",
                            JoinedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sandra Todorović",
                            PreferredPosition = 4,
                            Role = 2,
                            SecondaryPosition = 0
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("SponsorshipAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "esports@ht.hr",
                            ContactPhone = "+385 1 111 2222",
                            ContractEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HT Telekom",
                            SponsorshipAmount = 5000.00m,
                            Website = "https://www.t.ht.hr"
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "sponsorships@razer.com",
                            ContactPhone = "+1 800 123 4567",
                            ContractEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer",
                            SponsorshipAmount = 8000.00m,
                            Website = "https://www.razer.com"
                        },
                        new
                        {
                            Id = 3,
                            ContactEmail = "esports@redbull.com",
                            ContactPhone = "+43 662 6582 0",
                            ContractEnd = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Red Bull",
                            SponsorshipAmount = 10000.00m,
                            Website = "https://www.redbull.com"
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRosterConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = 1,
                            IsRosterConfirmed = true,
                            ManagerId = 1,
                            Name = "Zagreb Dragons",
                            RegisteredAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CoachId = 2,
                            IsRosterConfirmed = true,
                            ManagerId = 2,
                            Name = "Split Warriors",
                            RegisteredAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CoachId = 3,
                            IsRosterConfirmed = false,
                            ManagerId = 3,
                            Name = "Rijeka Titans",
                            RegisteredAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrizePool")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spring esports tournament",
                            EndDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Format = 0,
                            Name = "Spring Split 2025",
                            PrizePool = 25000m,
                            RegistrationDeadline = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 0,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Main summer tournament",
                            EndDate = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Format = 1,
                            Name = "Summer Championship 2025",
                            PrizePool = 50000m,
                            RegistrationDeadline = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 3,
                            VenueId = 2
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.TournamentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentDocuments");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BookingFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 35",
                            BookingFrom = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingTo = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 500,
                            City = "Zagreb",
                            ContactEmail = "contact@zagrebesports.hr",
                            ContactPhone = "+385 1 234 5678",
                            IsAvailable = true,
                            Name = "Zagreb Esports Arena"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Domovinskog rata 12",
                            BookingFrom = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingTo = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 300,
                            City = "Split",
                            ContactEmail = "info@splitgaming.hr",
                            ContactPhone = "+385 21 345 6789",
                            IsAvailable = true,
                            Name = "Split Gaming Hub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Korzo 5",
                            BookingFrom = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingTo = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 200,
                            City = "Rijeka",
                            ContactEmail = "hello@rjekalanc.hr",
                            ContactPhone = "+385 51 456 7890",
                            IsAvailable = true,
                            Name = "Rijeka LAN Center"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeamPlayers", b =>
                {
                    b.Property<int>("PlayersListId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("PlayersListId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamPlayers");

                    b.HasData(
                        new
                        {
                            PlayersListId = 1,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 2,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 3,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 4,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 5,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 6,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 7,
                            TeamsId = 1
                        },
                        new
                        {
                            PlayersListId = 8,
                            TeamsId = 2
                        },
                        new
                        {
                            PlayersListId = 9,
                            TeamsId = 2
                        },
                        new
                        {
                            PlayersListId = 10,
                            TeamsId = 2
                        },
                        new
                        {
                            PlayersListId = 11,
                            TeamsId = 2
                        },
                        new
                        {
                            PlayersListId = 12,
                            TeamsId = 2
                        });
                });

            modelBuilder.Entity("TournamentSponsors", b =>
                {
                    b.Property<int>("SponsorsListId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("SponsorsListId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentSponsors");

                    b.HasData(
                        new
                        {
                            SponsorsListId = 1,
                            TournamentId = 1
                        },
                        new
                        {
                            SponsorsListId = 2,
                            TournamentId = 1
                        },
                        new
                        {
                            SponsorsListId = 2,
                            TournamentId = 2
                        },
                        new
                        {
                            SponsorsListId = 3,
                            TournamentId = 2
                        });
                });

            modelBuilder.Entity("TournamentTeams", b =>
                {
                    b.Property<int>("TeamsListId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("TeamsListId", "TournamentId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentTeams");

                    b.HasData(
                        new
                        {
                            TeamsListId = 1,
                            TournamentId = 1
                        },
                        new
                        {
                            TeamsListId = 2,
                            TournamentId = 1
                        },
                        new
                        {
                            TeamsListId = 1,
                            TournamentId = 2
                        },
                        new
                        {
                            TeamsListId = 2,
                            TournamentId = 2
                        });
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Player", b =>
                {
                    b.OwnsOne("League_of_Legends_Tournament_Hosting.Models.AccountInformation", "AccountInformation", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.Property<int>("LeagueTier")
                                .HasColumnType("int");

                            b1.Property<int>("Region")
                                .HasColumnType("int");

                            b1.Property<string>("RiotTag")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SummonerName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("AccountInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Team", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.Tournament", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("League_of_Legends_Tournament_Hosting.Models.TournamentDocument", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamPlayers", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentSponsors", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Sponsor", null)
                        .WithMany()
                        .HasForeignKey("SponsorsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentTeams", b =>
                {
                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("League_of_Legends_Tournament_Hosting.Models.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
